---
name: Get version
on:
  workflow_dispatch:
    inputs:
      versionName:
        description: 'Version (ie 5.5.0)'
        required: false
jobs:
  checkversion:
    name: Check version
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Get version
        # id must be specified to retrieve the output of the step
        id: version-step
        uses: michmich112/extract-version@main
        with:
          version-file: "package.json"
          schema: major.minor.build
      - name: Set version
        id: set-version
        run: |
          if [ "${{ github.event.inputs.versionName }}" == "" ]; then
            echo ::set-output name=version::${{ steps.version-step.outputs.version }}
          else
            echo ::set-output name=version::${{ github.event.inputs.versionName }}
          fi
      - name: Test version
        run: echo ${{ steps.set-version.outputs.version }}